# Generated by Django 4.2.19 on 2025-02-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_per_unit_ingredients_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.TextField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitems')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchases',
            name='menu_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitems'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
